#-------------------------------------------
# InvoiceShelf PostgresSQL docker-compose variant
# Repo : https://github.com/InvoiceShelf/docker
#-------------------------------------------

services:
  database:
    container_name: invoiceshelf-pgsql
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=somepass
      - POSTGRES_USER=invoiceshelf
      - POSTGRES_DB=invoiceshelf
    volumes:
      - invoiceshelf_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - invoiceshelf
    restart: unless-stopped

  webapp:
    image: invoiceshelf/invoiceshelf:nightly
    container_name: invoiceshelf-variant-pgsql
    environment:
      - APP_NAME=InvoiceShelf
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8090
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=invoiceshelf
      - DB_USERNAME=invoiceshelf
      - DB_PASSWORD=somepass
      - DB_PASSWORD_FILE=
      - SESSION_DOMAIN=localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:8090
    volumes:
      - invoiceshelf_storage:/var/www/html/storage/
      - invoiceshelf_modules:/var/www/html/Modules/
    ports:
      - "8090:8080" # 8090 is the public port.
    networks:
      - invoiceshelf
    restart: unless-stopped
    depends_on:
      - database

networks:
  invoiceshelf:

volumes:
  invoiceshelf_postgres:
  invoiceshelf_storage:
  invoiceshelf_modules:
